# The 'type' should be "label" for short meta tags and "text" for ones which
# could get longer, especially ones which use a labelarea field instead of a
# labelfield.

metatag.metatag_tag.epa_title:
  type: label
  label: 'Title'
metatag.metatag_tag.epa_description:
  type: text
  label: 'Description'
metatag.metatag_tag.epa_channel:
  type: label
  label: 'Channel'
metatag.metatag_tag.epa_contenttype:
  type: label
  label: 'Content Type'
metatag.metatag_tag.epa_coverage:
  type: label
  label: 'Geographic Locations'
metatag.metatag_tag.epa_created:
  type: label
  label: 'Date Created'
metatag.metatag_tag.epa_creator:
  type: label
  label: 'Content Creator'
metatag.metatag_tag.epa_language:
  type: label
  label: 'Content language'
metatag.metatag_tag.epa_modified:
  type: label
  label: 'Date Modified'
metatag.metatag_tag.epa_pubnumber:
  type: label
  label: 'Publication Number'
metatag.metatag_tag.epa_regulation:
  type: label
  label: 'Environmental Laws, Regulations & Treaties'
metatag.metatag_tag.epa_reviewed:
  type: label
  label: 'Date Reviewed'
metatag.metatag_tag.epa_type:
  type: label
  label: 'Type'
metatag.metatag_tag.epa_webarea:
  type: label
  label: 'Web Area'
